添加配方
jenkins-zh/docker-zh pull request #16
Opened 2020-03-15 13:40 UTC by yJunS

2020-03-15 14:39 UTC, LinuxSuRen requested changes
PR title 尽量描述的清楚一些。
增加一个新的配方后，需要在 readme 文件中有对应的记录，方便大家了解。另外，可以执行下面的命令在进行测试打包，并把构建出来的镜像可以推送到自己的 docker hub 上，方面大家 review
`make darwin && ./cj build --username BINTRAY_USER --token BINTRAY_TOKEN --docker-username DOCKER_HUB_USER --docker-token secrets.DOCKER_HUB_TOKEN`

其中 BINTRAY_USER 和 BINTRAY_TOKEN 可以在https://bintray.com/ 上申请账号。

2020-03-15 14:51 UTC, LinuxSuRen requested changes
代码有一部分是写死，我上面说的方法貌似还无法用于构建测试包。可以用下面的方式来构建镜像：
首先把 `{{.version}}` 手动替换为特定的版本，例：`2.204.5`，然后执行命令：
`jcli cwp --config-path formulas/pipeline-node.yaml --version 1.0 --tmp-dir tmp`
这时候，可以把镜像tag后推送到自己的 docker hub 上

2020-03-15 14:51 UTC, LinuxSuRen commented on formulas/pipeline-node.yaml
> +      artifactId: "git"
缩进有问题

2020-03-15 16:35 UTC, yJunS commented on formulas/pipeline-node.yaml
> +      artifactId: "git"
Error: unknown command "cwp" for "jcli"

2020-03-15 23:20 UTC, LinuxSuRen commented on formulas/pipeline-node.yaml
> +      artifactId: "git"
忘记说了，还得用 dev 版本的：
```
wget https://dl.bintray.com/jenkins-zh/generic/jenkins-cli/dev/jcli-linux-amd64.tar.gz
          tar xzvf jcli-linux-amd64.tar.gz
```

2020-03-19 11:48 UTC, LinuxSuRen commented on formulas/pipeline-node.yaml
> +    version: 2.204.5
这里确定要写死？

2020-03-19 13:32 UTC, yJunS commented on formulas/pipeline-node.yaml
> +    version: 2.204.5
忘改回去了。。

2020-04-08 08:47 UTC, LinuxSuRen commented
git 提交记录，麻烦检查下

2020-04-08 15:32 UTC, yJunS commented
> git 提交记录，麻烦检查下

已更新

2020-09-15 07:59 UTC, LinuxSuRen commented
该配方并没有特殊的内容，暂时关闭

2020-09-15 07:59 UTC, closed without merging