add formulas: maven
jenkins-zh/docker-zh pull request #23
Opened 2020-03-19 10:20 UTC by donhui

测试镜像：
`docker run -p 8080:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" donhui/jenkins-pipeline-maven:2.226`

2020-03-19 11:46 UTC, LinuxSuRen requested changes

2020-03-19 11:46 UTC, LinuxSuRen commented on maven-init.groovy
> +hudsonRealm.createAccount('admin', '9YxwvCOUPML8onXF')
把账号密码写死的话，作为演示使用还可以。如果想要更加通用的话，可能就不太合适了。

2020-03-19 12:27 UTC, LinuxSuRen commented on casc-maven.yaml
> +                    id: "3.6.3"
这个配方和 [pipeline](https://github.com/jenkins-zh/docker-zh/blob/master/formulas/pipeline.yaml) 对比的话，只是多了这部分，我们是否可以在启动 pipeline 这个配方的 Jenkins 的时候，给这个 casc 配置文件也能满足这个需求。

2020-03-19 12:36 UTC, donhui commented on maven-init.groovy
> +hudsonRealm.createAccount('admin', '9YxwvCOUPML8onXF')
这个去掉了

2020-03-19 12:36 UTC, donhui commented on casc-maven.yaml
> +                    id: "3.6.3"
还有一个 git 插件

2020-03-19 12:37 UTC, LinuxSuRen commented on casc-maven.yaml
> +                    id: "3.6.3"
流水线中， git 也是常用的，那是否可以把 git 插件加到流水线里呢？

2020-03-19 12:39 UTC, donhui commented on casc-maven.yaml
> +                    id: "3.6.3"
也可以，那 pipeline 的也可以把 maven 的配置加上么？

2020-03-19 12:40 UTC, donhui commented on casc-maven.yaml
> +                    id: "3.6.3"
可能不仅仅是要 Maven 的，Gradle 也需要

2020-03-19 12:41 UTC, LinuxSuRen commented on casc-maven.yaml
> +                    id: "3.6.3"
如果只是加个工具的配置，我感觉还是可以的

2020-03-19 12:44 UTC, LinuxSuRen commented on casc-maven.yaml
> +                    id: "3.6.3"
另外，需要对配方所包含的配置做一个介绍，master 上的那个表格可能就不太够了

2020-03-19 12:47 UTC, donhui commented on casc-maven.yaml
> +                    id: "3.6.3"
嗯，那我把这个 PR 关掉，修改下 Pipeline 的配置吧

2020-03-19 13:07 UTC, donhui commented on casc-maven.yaml
> +                    id: "3.6.3"
我试着改了下 Pipeline 的 yaml，出现了一堆插件版本不兼容～～
这个没想到好的解决方式，可能这个 jenkins 版本没问题，另一个 jenkins 版本就会有问题
或者，这种一次性的我们不用配方了，只是简体中文插件用配方？
忧伤～～

2020-03-19 13:10 UTC, LinuxSuRen commented
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你用的哪个镜像测试的？把命令贴一下，我看看
 
    

    On 03/19/2020 21:08，Donghui Wang<notifications@github.com> wrote： 




@donhui commented on this pull request.







In casc-maven.yaml:

> @@ -0,0 +1,9 @@

+tool:

+  maven:

+    installations:

+      - name: "M3"

+        properties:

+          - installSource:

+              installers:

+                - maven:

+                    id: "3.6.3"



我试着改了下 Pipeline 的 yaml，出现了一堆插件版本不兼容～～

这个没想到好的解决方式，可能这个 jenkins 版本没问题，另一个 jenkins 版本就会有问题

或者，这种一次性的我们不用配方了，只是简体中文插件用配方？

忧伤～～



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-19 13:13 UTC, donhui commented
jcli cwp --config-path formulas/pipeline.yaml --tmp-dir tmp/ --value-set version=2.226

docker run -p 8080:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkinszh/jenkins-pipeline:2.226

日志输出比较长：
```
192:docker-zh donghui9$ docker run -p 8080:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkinszh/jenkins-pipeline:2.226
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-03-19 13:04:52.506+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @162ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-03-19 13:04:52.625+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2020-03-19 13:04:53.266+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-03-19 13:04:53.335+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.27.v20200227; built: 2020-02-27T18:37:21.340Z; git: a304fd9f351f337e7c0e2a7c28878dd536149c6c; jvm 1.8.0_242-b08
2020-03-19 13:04:53.588+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-03-19 13:04:53.630+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-03-19 13:04:53.630+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-03-19 13:04:53.635+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2020-03-19 13:04:54.031+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-03-19 13:04:54.173+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@4628b1d3{Jenkins v2.226,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2020-03-19 13:04:54.192+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@24c1b2d2{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-03-19 13:04:54.192+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @1848ms
2020-03-19 13:04:54.194+0000 [id=21]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2020-03-19 13:04:55.742+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-03-19 13:04:56.074+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/trilead-api.jpi
2020-03-19 13:04:56.109+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/bouncycastle-api.jpi
2020-03-19 13:04:56.165+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/command-launcher.jpi
2020-03-19 13:04:56.173+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/jdk-tool.jpi
2020-03-19 13:04:57.325+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-03-19 13:04:57.390+0000 [id=26]    INFO    j.b.a.SecurityProviderInitializer#addSecurityProvider: Initializing Bouncy Castle security provider.
2020-03-19 13:04:57.575+0000 [id=26]    INFO    j.b.a.SecurityProviderInitializer#addSecurityProvider: Bouncy Castle security provider initialized.
2020-03-19 13:04:57.701+0000 [id=32]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git client plugin v3.0.0 (git-client)
java.io.IOException: Failed to load: Jenkins Git client plugin (3.0.0)
 - Update required: Jenkins Apache HttpComponents Client 4.x API Plugin (4.5.5-3.0) to be updated to 4.5.10-1.0 or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-19 13:04:57.702+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins GIT server Plugin v1.7 (git-server)
java.io.IOException: Failed to load: Jenkins GIT server Plugin (1.7)
 - Failed to load: Jenkins Git client plugin (3.0.0)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-19 13:04:57.703+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Shared Groovy Libraries v2.11 (workflow-cps-global-lib)
java.io.IOException: Failed to load: Pipeline: Shared Groovy Libraries (2.11)
 - Failed to load: Jenkins Git client plugin (3.0.0)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-03-19 13:04:57.710+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative v1.6.0 (pipeline-model-definition)
java.io.IOException: Failed to load: Pipeline: Declarative (1.6.0)
 - Failed to load: Pipeline: Shared Groovy Libraries (2.11)
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at jav [...]

2020-03-19 13:19 UTC, LinuxSuRen commented
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    看起来，把- Update required: Jenkins Apache HttpComponents Client 4.x API Plugin (4.5.5-3.0) to be updated to 4.5.10-1.0 or higher这个升级了就可以吧
 
    

    On 03/19/2020 21:14，Donghui Wang<notifications@github.com> wrote： 




jcli cwp --config-path formulas/pipeline.yaml --tmp-dir tmp/ --value-set version=2.226

docker run -p 8080:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkinszh/jenkins-pipeline:2.226

日志输出比较长：

192:docker-zh donghui9$ docker run -p 8080:8080 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" jenkinszh/jenkins-pipeline:2.226

Running from: /usr/share/jenkins/jenkins.war

webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")

2020-03-19 13:04:52.506+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @162ms to org.eclipse.jetty.util.log.JavaUtilLog

2020-03-19 13:04:52.625+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file

2020-03-19 13:04:53.266+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath

2020-03-19 13:04:53.335+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: jetty-9.4.27.v20200227; built: 2020-02-27T18:37:21.340Z; git: a304fd9f351f337e7c0e2a7c28878dd536149c6c; jvm 1.8.0_242-b08

2020-03-19 13:04:53.588+0000 [id=1]     INFO    o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

2020-03-19 13:04:53.630+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0

2020-03-19 13:04:53.630+0000 [id=1]     INFO    o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults

2020-03-19 13:04:53.635+0000 [id=1]     INFO    o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms

2020-03-19 13:04:54.031+0000 [id=1]     INFO    hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")

2020-03-19 13:04:54.173+0000 [id=1]     INFO    o.e.j.s.handler.ContextHandler#doStart: Started w.@4628b1d3{Jenkins v2.226,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}

2020-03-19 13:04:54.192+0000 [id=1]     INFO    o.e.j.server.AbstractConnector#doStart: Started ServerConnector@24c1b2d2{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}

2020-03-19 13:04:54.192+0000 [id=1]     INFO    org.eclipse.jetty.server.Server#doStart: Started @1848ms

2020-03-19 13:04:54.194+0000 [id=21]    INFO    winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled

2020-03-19 13:04:55.742+0000 [id=28]    INFO    jenkins.InitReactorRunner$1#onAttained: Started initialization

2020-03-19 13:04:56.074+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/trilead-api.jpi

2020-03-19 13:04:56.109+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/bouncycastle-api.jpi

2020-03-19 13:04:56.165+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/command-launcher.jpi

2020-03-19 13:04:56.173+0000 [id=33]    INFO    hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/jenkins_home/plugins/jdk-tool.jpi

2020-03-19 13:04:57.325+0000 [id=31]    INFO    jenkins.InitReactorRunner$1#onAttained: Listed all plugins

2020-03-19 13:04:57.390+0000 [id=26]    INFO    j.b.a.SecurityProviderInitializer#addSecurityProvider: Initializing Bouncy Castle security provider.

2020-03-19 13:04:57.575+0000 [id=26]    INFO    j.b.a.SecurityProviderInitializer#addSecurityProvider: Bouncy Castle security provider initialized.

2020-03-19 13:04:57.701+0000 [id=32]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git client plugin v3.0.0 (git-client)

java.io.IOException: Failed to load: Jenkins Git client plugin (3.0.0)

 - Update required: Jenkins Apache HttpComponents Client 4.x API Plugin (4.5.5-3.0) to be updated to 4.5.10-1.0 or higher

        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)

        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)

        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)

        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)

        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)

        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)

        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

2020-03-19 13:04:57.702+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins GIT server Plugin v1.7 (git-server)

java.io.IOException: Failed to load: Jenkins GIT server Plugin (1.7)

 - Failed to load: Jenkins Git client plugin (3.0.0)

        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)

        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)

        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)

        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)

        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)

        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)

        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

2020-03-19 13:04:57.703+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Shared Groovy Libraries v2.11 (workflow-cps-global-lib)

java.io.IOException: Failed to load: Pipeline: Shared Groovy Libraries (2.11)

 - Failed to load: Jenkins Git client plugin (3.0.0)

        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)

        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)

        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)

        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)

        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)

        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)

        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)

        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

2020-03-19 13:04:57.710+0000 [id=33]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Declarative v1.6.0 (pipeline-model-definition)

java.io.IOException: Failed to load: Pipeline: Declarative (1.6.0)

 - Failed to load: Pipeline: Shared Groovy Libraries (2.11)

        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)

        at hudson.PluginManager$2$1$1.run(PluginManager.java:546)

        at org.jvnet. [...]

2020-03-19 13:21 UTC, donhui commented
理论上是这样，但是没法保证其他版本的 jenkins 也兼容

2020-03-19 13:23 UTC, LinuxSuRen commented
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    但是，这个报错和 Jenkins 的版本好像是没有关系的。
 
    

    On 03/19/2020 21:22，Donghui Wang<notifications@github.com> wrote： 




理论上是这样，但是没法保证其他版本的 jenkins 也兼容



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-19 13:33 UTC, donhui commented
我感觉这个通过 maven 下载，貌似和通过 install-plugins.sh 下载貌似处理冲突的方式不一样
我之前通过 install-plugins.sh 下载就好的，通过 maven 下载就会有冲突

2020-03-19 13:36 UTC, LinuxSuRen commented
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    确实是不太一样的。
 
    

    On 03/19/2020 21:34，Donghui Wang<notifications@github.com> wrote： 




我感觉这个通过 maven 下载，貌似和通过 install-plugins.sh 下载貌似处理冲突的方式不一样

我之前通过 install-plugins.sh 下载就好的，通过 maven 下载就会有冲突



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-03-19 14:57 UTC, donhui commented
可能用了简体中文插件的镜像，自动安装工具的功能坏掉了：
```
2020-03-19 14:48:14.337+0000 [id=47]    WARNING h.m.DownloadService$Downloadable#updateNow: No tool installer metadata found for hudson.tasks.Maven.MavenInstaller
2020-03-19 14:48:14.433+0000 [id=47]    WARNING h.m.DownloadService$Downloadable#updateNow: No tool installer metadata found for hudson.tools.JDKInstaller
```

参考：
https://issues.jenkins-ci.org/browse/JENKINS-36957
https://issues.jenkins.io/browse/JENKINS-32831

![image](https://user-images.githubusercontent.com/5702065/77080929-e3bed700-6a34-11ea-8148-6f5abcab6cd9.png)

2020-03-19 23:56 UTC, LinuxSuRen commented
确实是有问题，我看了大致是由于缺少一些文件。目前还在修复。可以参考这里 https://github.com/jenkins-zh/update-center-mirror/blob/master/.github/workflows/mirror.yaml

2020-03-20 11:53 UTC, yJunS commented on casc-maven.yaml
> +                    id: "3.6.3"
目前生成确实感觉会很费劲，就目前而言感觉更繁琐了

2020-03-28 12:28 UTC, LinuxSuRen commented
上面无法安装 maven 的问题已经修复了。

2020-03-28 12:30 UTC, donhui commented
嗯，我这边再验证下

2020-03-28 12:47 UTC, LinuxSuRen commented
上次讨论的结果，我们可以把maven的配置加到 pipeline 的那个配方中

2020-03-28 12:56 UTC, donhui commented
重新提了一个 https://github.com/jenkins-zh/docker-zh/pull/28 ，review 下

2020-03-28 12:56 UTC, donhui commented
这个可以关掉

2020-04-02 01:11 UTC, LinuxSuRen commented
在 #28 这里已经包含了当前 PR 的内容

2020-04-02 01:11 UTC, closed without merging